name = "EHTIDFE"
uuid = "6f636263-92f2-4d33-8617-44fbc15b3a39"
authors = ["Rohan Dahale", "Ilje Cho", "Guang-Yao Zhao", "Iniyan Natarajan"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
